### ISSUE TITLE
Wrong entry point

### ISSUE THREAD

**Issue by myint** [jstasiak/travis-solo#3]
``` bash
$ pip install --user travis-solo
$ travis-solo 
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pkg_resources.py", line 2019, in load
    entry = getattr(entry,attr)
AttributeError: 'module' object has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myint/Library/Python/3.3/bin/travis-solo", line 9, in <module>
    load_entry_point('travis-solo==0.0.4', 'console_scripts', 'travis-solo')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pkg_resources.py", line 2310, in load_entry_point
    return ep.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pkg_resources.py", line 2021, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'travis_solo' from '/Users/myint/Library/Python/3.3/lib/python/site-packages/travis_solo.py'> has no 'main' attribute
```

**Comment by jstasiak** [comment]
Ugh, missed it. Thanks for pointing that out!
